#!/bin/sh
[ -n "${IPKG_INSTROOT}" ] || {
	( . /etc/uci-defaults/luci-gmediarender ) && rm -f /etc/uci-defaults/luci-gmediarender
	chmod 755 /etc/init.d/gmediarender >/dev/null 2>&1
	/etc/init.d/gmediarender enable >/dev/null 2>&1
	exit 0
}
