--- Makefile	2014-03-10 10:56:26.000000000 +0800
+++ Makefile	2014-03-10 11:00:51.000000000 +0800
@@ -49,7 +49,7 @@
   SECTION:=libs
   SUBMENU:=SSL
   CATEGORY:=Libraries
-  DEPENDS:=+zlib
+  DEPENDS:=+zlib +libpthread
   TITLE+= (libraries)
   MENU:=1
 endef
@@ -137,7 +137,7 @@
 		depend
 endef
 
-TARGET_CFLAGS += $(FPIC)
+TARGET_CFLAGS += $(FPIC) -DOPENSSL_THREADS -D_REENTRANT -D_THREAD_SAFE -D_THREADSAFE -pthread
 
 define Build/Compile
 	+$(MAKE) $(PKG_JOBS) -C $(PKG_BUILD_DIR) \
@@ -196,5 +196,5 @@
 	$(INSTALL_BIN) $(PKG_INSTALL_DIR)/usr/bin/openssl $(1)/usr/bin/
 endef
 
-$(eval $(call BuildPackage,libopenssl))
+$(eval $(call BuildPackage,libopenssl,+libpthread))
 $(eval $(call BuildPackage,openssl-util))
