#!/bin/sh
[ -n "${IPKG_INSTROOT}" ] || {
	( . /etc/uci-defaults/luci-upnpaudioplayer ) && rm -f /etc/uci-defaults/luci-upnpaudioplayer
	chmod 755 /etc/init.d/upnpaudioplayer >/dev/null 2>&1
	/etc/init.d/upnpaudioplayer enable >/dev/null 2>&1
	exit 0
}
