#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@gmediarender[-1]
	add ucitrack gmediarender
	set ucitrack.@gmediarender[-1].init=gmediarender
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
