#!/bin/sh
[ -n "${IPKG_INSTROOT}" ] || {
	( . /etc/uci-defaults/luci-goagent ) && rm -f /etc/uci-defaults/luci-goagent
	chmod 755 /etc/init.d/goagent >/dev/null 2>&1
	/etc/init.d/goagent enable >/dev/null 2>&1
	exit 0
}
