#!/bin/sh
[ -n "${IPKG_INSTROOT}" ] || {
	( . /etc/uci-defaults/luci-shairport ) && rm -f /etc/uci-defaults/luci-shairport
	chmod 755 /etc/init.d/shairport >/dev/null 2>&1
	/etc/init.d/shairport enable >/dev/null 2>&1
	exit 0
}
